### ISSUE TITLE
Swift 5.0 support

### ISSUE THREAD

**Issue by andrewjlow** [raginmari/RAGTextField#3]
Hi there,

Could you please provide support for Swift 5.0, please?

I've added your pod into my project and I am getting the following errors:

![image](https://user-images.githubusercontent.com/5027396/58223578-9d89e000-7d5d-11e9-8409-22c714d5bc9c.png)

Thank you!

**Comment by raginmari** [comment]
I've already done that on a local branch. The change will be committed to master soon.

**Comment by raginmari** [comment]
Please try version 0.13.0.
